---
# tasks file for nodejs

- name: Installing epel
  shell: amazon-linux-extras install -y epel
  args:
    executable: /bin/bash

- name: Installing Python3
  yum:
    state: installed
    name:
      - python3

- name: Installing node and npm
  yum:
    name: "{{ item }}"
    enablerepo: epel
    state: installed
  with_items:
    - nodejs
    - npm